options:
  max-time: 30

definitions:
  steps:
    - step: &python-format
        name: Python format
        image: python:3.12
        script:
          - python -m pip install --upgrade pip
          - pip install ruff
          - ruff format --check .
    - step: &js-lint-test-build
        name: JS lint, tests, and build
        image: node:22.11.0 # using 22.11.0 because the experimental feature for importing ESM (enabled by default starting with node 22.12.0) significantly slows test execution in the pipeline (https://github.com/vitest-dev/vitest/issues/7302)
        caches:
          - node
        size: 2x # more memory to accomodate docker container for sonarcloud
        script:
          - cd org.knime.python3.scripting.nodes/js-src
          - npm ci
          - npm run type-check
          - npm run ci:lint-format
          - npm run coverage
          - npm run audit
          - npm run build
        artifacts:
          - org.knime.python3.scripting.nodes/js-src/dist/**

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step: *python-format
          - step: *js-lint-test-build
  branches:
    '{master,releases/*}':
      - step: *js-lint-test-build
