{% set version =  "5.3.0" %}

package:
  name: knime-extension
  version: {{ version }}

# https://github.com/conda/conda-build/pull/5112
source:
  path: ..

requirements:
  build:
    - python=3.9
    - pip
    - setuptools
    - build
    - wheel
  run:
    - python>=3.9

build:
  noarch: python
  string: py{{ python | replace(".", "") }}_{{time.strftime("%Y%m%d%H%M").strip()}}

test:
  imports:
    - knime
    - knime.api
    - knime.api.schema
    - knime.api.table
    - knime.api.types
    - knime.api.views
    - knime.extension
    - knime.extension.nodes
    - knime.extension.parameter
    - knime.extension.version
    - knime.extension.testing
    - knime_extension
  requires:
    - pandas
    - python-dateutil
    - pytz
    - requests
    - pytest
  commands:
    - pytest .
  source_files:
    - recipe/node_with_test.py
    - recipe/test/plugin.xml
    - recipe/test/knime/types/chemistry.py

about:
  home: https://knime.com
  author: KNIME GmbH, Germany
  license: GPLv3
  license_file: ../LICENSE.TXT
  summary: API for KNIME Python extension development to facilitate autocompletion
  description: API for KNIME Python extension development to facilitate autocompletion

extra:
  maintainers:
   - Team Rakete (team-rakete@knime.com)
